#!/bin/bash
# Patch script für card-aware parallax system in HandController.cs

# Backup erstellen
cp /Users/exqbitmac/TimeBlade/Assets/UI/HandController.cs /Users/exqbitmac/TimeBlade/Assets/UI/HandController.cs.backup_before_cardaware

echo "=== Card-Aware Parallax Patch für HandController.cs ==="
echo ""
echo "WICHTIG: Dieses Script muss manuell angewendet werden, da die HandController.cs Datei zu groß ist."
echo ""
echo "Folgende Schritte sind notwendig:"
echo ""
echo "1. Öffne HandController.cs in deinem Code-Editor"
echo ""
echo "2. Füge folgende neuen Variablen nach den bestehenden Parallax-Variablen hinzu (ca. Zeile 125):"
echo "   // Card-aware parallax variables"
echo "   private float initialCardNormalizedPosition = 0.5f; // 0=left, 1=right"
echo "   private float initialHandOffsetForCard = 0f; // The offset the hand should have for the touched card"
echo "   private float maxAllowedLeftMovement = 0f; // How much the hand can move left from initial"
echo "   private float maxAllowedRightMovement = 0f; // How much the hand can move right from initial"
echo ""
echo "3. In der HandleTouchStart Methode, nach der Zeile:"
echo "   touchStartScreenPos = position;"
echo "   "
echo "   Füge hinzu:"
echo "   // CARD-AWARE PARALLAX: Initialize based on touched card position"
echo "   InitializeCardAwareParallax(touchedCard);"
echo ""
echo "4. Füge die neue InitializeCardAwareParallax Methode vor UpdateParallaxHandShift ein."
echo "   Der Code befindet sich in: /Users/exqbitmac/TimeBlade/HandController_CardAwareParallax.cs"
echo ""
echo "5. Ersetze die KOMPLETTE UpdateParallaxHandShift Methode mit der neuen Version"
echo "   aus der HandController_CardAwareParallax.cs Datei."
echo ""
echo "6. Stelle sicher, dass die Logging-Einstellung 'logParallaxDetails' auf true gesetzt ist,"
echo "   um die neue card-aware Funktionalität zu testen."
echo ""
echo "Die alte UpdateParallaxHandShift Methode beginnt mit:"
echo "    /// <summary>"
echo "    /// NEUE METHODE: Aktualisiert die Parallax-Verschiebung der Hand basierend auf Finger-Position"
echo "    /// Uses SIMPLE ABSOLUTE PARALLAX: Just invert finger position relative to touch start"
echo "    /// </summary>"
echo ""
echo "Und sollte komplett ersetzt werden mit beiden Methoden aus HandController_CardAwareParallax.cs"
